### ISSUE TITLE
Another performant implementation of line clipping

### ISSUE THREAD

**Issue by rowanwins** [w8r/liang-barsky#1]
Gday @w8r 

Was doing some looking at line clipping algorithms last night, particularly I was hunting for clipping lines to concave polygons.

In my hunt I came across another bbox clipping algorithm which seemed pretty simple and the paper claimed it to be more performant than liang-barsky so I thought I'd have a go at implementing it. 

So here is my [rough first cut](https://github.com/rowanwins/kwc-lineclip). The first benchmark looks good and there are a couple of spots of code that could be improved for better performance.

Just thought I'd let you know given that you've inspired me in this whole clipping field :) 

Cheers
Rowan

And PS I did track down a [paper for clipping lines to concave polys](http://ieeexplore.ieee.org/document/5364626/?reload=true), I'll have a go at implementing this at some stage, and will let you know when there is something to look at.

PPS Feel free to close the issue, just thought this was the easiest way to let you know :)

**Comment by w8r** [comment]
That's so cool! Can I help?

**Comment by rowanwins** [comment]
With the concave poly implementation or the kwc implementation or both? Either way of course the answer is yes!

In regards to concave poly implementation I'm probably a week away from looking into but I can send you the paper via email if you'd like to have a read.

For the kwc implementation Im happy to make you a contributor to the repo if you'd like. 
- Obviously some work needs to be done on handling polylines with multiple segments. 
  - I'd also like to handle multiple polylines similar to polyclip
- I'd also like to build a demo site, I'll probably follow a similar approach to what I've done [here](https://github.com/rowanwins/visibility-graph). 
- And the tests need completing, they can probably largely be copied from your liang-barksy lib.
